---
- hosts: 172.31.26.217  
  become: yes
  tasks: 
  - include_tasks: myfiles.yml
  - name: creat a folder
    file: 
      path: /home/ubuntu/myfolder
      state: directory
  - name: i want to copy files
    copy: 
      src: mystaticfiles
      dest: /home/ubuntu/mystaticfiles.txt
